name: Fetch Samsung Board DTS

on:
  workflow_dispatch: # تشغيل يدوي
  push: # تشغيل عند الدفع بالكود

jobs:
  fetch-dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Samsung Directory
        run: |
          mkdir kernel_dts && cd kernel_dts
          git init
          git remote add origin https://github.com/ioiwww/android_kernel_samsung_exynos9820.git
          
          # تفعيل السحب الجزئي للمجلد الجديد (samsung)
          git config core.sparseCheckout true
          echo "arch/arm64/boot/dts/samsung/" >> .git/info/sparse-checkout
          
          # سحب آخر نسخة فقط بسرعة عالية لتجنب التعليق
          git pull --depth 1 origin lineage-23.2
          
      - name: Upload DTS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Samsung-Board-DTS
          path: kernel_dts/arch/arm64/boot/dts/samsung/
          retention-days: 5
